Repository maemre/compiler-explorer, pull requests merged in 2023-08, with the labels that each got.

#7 Call the wasm version of the compiler instead of the API call to the compiler
  static/compiler-service.ts
  static/process-asm.ts
Labels: enhancement

#14 Add documentation for tests
  test/cflat-tests.ts
Labels: documentation

#17 Arbie: Work on Issue #11
  lib/compilers/cflat.ts
  static/compiler-service.ts
  static/modes/cflat-mode.ts
  test/cflat-tests.ts
Labels: documentation

#19 Update cflat.defaults.properties
  etc/config/cflat.defaults.properties
Labels: bug, enhancement
